name: xterm
description: xterm.dart is a fast and fully-featured terminal emulator for
  Flutter applications, with support for mobile and desktop platforms.
version: 4.0.0
homepage: https://github.com/TerminalStudio/xterm.dart

environment:
  sdk: 3.8.1
  flutter: 3.32.4

dependencies:
  convert: ^3.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  zmodem: ^0.0.6

dev_dependencies:
  dartx: ^1.2.0
  flutter_bloc: ^9.1.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  dart_code_metrics: ">=5.0.0 <5.2.0"
  build_runner: ^2.1.1
  test_api: ^0.7.4
